/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Activity = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'image' : ExternalBlob,
});
export const Donation = IDL.Record({
  'donorName' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addContactInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addDonation' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'getActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'getDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getFoundationInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'description' : IDL.Text,
          'email' : IDL.Text,
          'address' : IDL.Text,
          'phone' : IDL.Text,
          'socialMedia' : IDL.Vec(IDL.Text),
        }),
      ],
      ['query'],
    ),
  'seedActivities' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Activity = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'image' : ExternalBlob,
  });
  const Donation = IDL.Record({
    'donorName' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addContactInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addDonation' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'getActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'getDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getFoundationInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'description' : IDL.Text,
            'email' : IDL.Text,
            'address' : IDL.Text,
            'phone' : IDL.Text,
            'socialMedia' : IDL.Vec(IDL.Text),
          }),
        ],
        ['query'],
      ),
    'seedActivities' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };