/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const MembershipType = IDL.Variant({
  'Lifetime' : IDL.Null,
  'Monthly' : IDL.Null,
  'Yearly' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const District = IDL.Record({
  'id' : IDL.Nat,
  'villageIds' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
});
export const Village = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'districtId' : IDL.Nat,
});
export const AssistanceRequest = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'description' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'requestType' : IDL.Text,
});
export const ContactInquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const DonationIntent = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'amount' : IDL.Text,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const MembershipApplication = IDL.Record({
  'id' : IDL.Nat,
  'status' : ApplicationStatus,
  'paymentConfirmed' : IDL.Bool,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'membershipType' : MembershipType,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAssistanceRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addContactInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addDistrict' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'addDonationIntent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addMembershipApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, MembershipType, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'addVillage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteDistrict' : IDL.Func([IDL.Nat], [], []),
  'deleteVillage' : IDL.Func([IDL.Nat], [], []),
  'editDistrict' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'editVillage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDistricts' : IDL.Func([], [IDL.Vec(District)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVillagesByDistrict' : IDL.Func([IDL.Nat], [IDL.Vec(Village)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAssistanceRequests' : IDL.Func(
      [],
      [IDL.Vec(AssistanceRequest)],
      ['query'],
    ),
  'listContactInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
  'listDonationIntents' : IDL.Func([], [IDL.Vec(DonationIntent)], ['query']),
  'listMembershipApplications' : IDL.Func(
      [IDL.Opt(ApplicationStatus)],
      [IDL.Vec(MembershipApplication)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
  'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const MembershipType = IDL.Variant({
    'Lifetime' : IDL.Null,
    'Monthly' : IDL.Null,
    'Yearly' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const District = IDL.Record({
    'id' : IDL.Nat,
    'villageIds' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
  });
  const Village = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'districtId' : IDL.Nat,
  });
  const AssistanceRequest = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'description' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'requestType' : IDL.Text,
  });
  const ContactInquiry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DonationIntent = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'amount' : IDL.Text,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const MembershipApplication = IDL.Record({
    'id' : IDL.Nat,
    'status' : ApplicationStatus,
    'paymentConfirmed' : IDL.Bool,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'membershipType' : MembershipType,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAssistanceRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addContactInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addDistrict' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'addDonationIntent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addMembershipApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, MembershipType, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'addVillage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteDistrict' : IDL.Func([IDL.Nat], [], []),
    'deleteVillage' : IDL.Func([IDL.Nat], [], []),
    'editDistrict' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'editVillage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDistricts' : IDL.Func([], [IDL.Vec(District)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVillagesByDistrict' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Village)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAssistanceRequests' : IDL.Func(
        [],
        [IDL.Vec(AssistanceRequest)],
        ['query'],
      ),
    'listContactInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
    'listDonationIntents' : IDL.Func([], [IDL.Vec(DonationIntent)], ['query']),
    'listMembershipApplications' : IDL.Func(
        [IDL.Opt(ApplicationStatus)],
        [IDL.Vec(MembershipApplication)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
    'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };