/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Village = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'districtId' : IDL.Nat,
});
export const District = IDL.Record({
  'id' : IDL.Nat,
  'villages' : IDL.Vec(Village),
  'name' : IDL.Text,
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Nat,
  'eventId' : IDL.Nat,
  'imageData' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'caption' : IDL.Text,
});
export const GalleryEvent = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'subtitle' : IDL.Text,
  'images' : IDL.Vec(GalleryImage),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDistrict' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'addGalleryEvent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addGalleryImage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addVillage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteDistrict' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteGalleryEvent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteGalleryImage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteVillage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDistricts' : IDL.Func([], [IDL.Vec(District)], ['query']),
  'getGalleryEvents' : IDL.Func([], [IDL.Vec(GalleryEvent)], ['query']),
  'getGalleryImagesByEvent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(GalleryImage)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVillagesByDistrict' : IDL.Func([IDL.Nat], [IDL.Vec(Village)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Village = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'districtId' : IDL.Nat,
  });
  const District = IDL.Record({
    'id' : IDL.Nat,
    'villages' : IDL.Vec(Village),
    'name' : IDL.Text,
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Nat,
    'eventId' : IDL.Nat,
    'imageData' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'caption' : IDL.Text,
  });
  const GalleryEvent = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'subtitle' : IDL.Text,
    'images' : IDL.Vec(GalleryImage),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDistrict' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'addGalleryEvent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addGalleryImage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addVillage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteDistrict' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteGalleryEvent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteGalleryImage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteVillage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDistricts' : IDL.Func([], [IDL.Vec(District)], ['query']),
    'getGalleryEvents' : IDL.Func([], [IDL.Vec(GalleryEvent)], ['query']),
    'getGalleryImagesByEvent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(GalleryImage)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVillagesByDistrict' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Village)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };