/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApplicationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface AssistanceRequest {
  'id' : bigint,
  'name' : string,
  'submittedAt' : bigint,
  'description' : string,
  'address' : string,
  'phone' : string,
  'requestType' : string,
}
export interface ContactInquiry {
  'id' : bigint,
  'name' : string,
  'submittedAt' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface District {
  'id' : bigint,
  'villageIds' : Array<bigint>,
  'name' : string,
}
export interface DonationIntent {
  'id' : bigint,
  'name' : string,
  'submittedAt' : bigint,
  'email' : string,
  'message' : string,
  'amount' : string,
}
export interface MembershipApplication {
  'id' : bigint,
  'status' : ApplicationStatus,
  'paymentConfirmed' : boolean,
  'name' : string,
  'submittedAt' : bigint,
  'email' : string,
  'address' : string,
  'phone' : string,
  'membershipType' : MembershipType,
}
export type MembershipType = { 'Lifetime' : null } |
  { 'Monthly' : null } |
  { 'Yearly' : null };
export type Result = { 'ok' : null } |
  { 'err' : string };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Village {
  'id' : bigint,
  'name' : string,
  'districtId' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAssistanceRequest' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'addContactInquiry' : ActorMethod<[string, string, string, string], bigint>,
  'addDistrict' : ActorMethod<[string], bigint>,
  'addDonationIntent' : ActorMethod<[string, string, string, string], bigint>,
  'addMembershipApplication' : ActorMethod<
    [string, string, string, string, MembershipType, boolean],
    bigint
  >,
  'addVillage' : ActorMethod<[bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteDistrict' : ActorMethod<[bigint], undefined>,
  'deleteVillage' : ActorMethod<[bigint], undefined>,
  'editDistrict' : ActorMethod<[bigint, string], undefined>,
  'editVillage' : ActorMethod<[bigint, string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDistricts' : ActorMethod<[], Array<District>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVillagesByDistrict' : ActorMethod<[bigint], Array<Village>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAssistanceRequests' : ActorMethod<[], Array<AssistanceRequest>>,
  'listContactInquiries' : ActorMethod<[], Array<ContactInquiry>>,
  'listDonationIntents' : ActorMethod<[], Array<DonationIntent>>,
  'listMembershipApplications' : ActorMethod<
    [[] | [ApplicationStatus]],
    Array<MembershipApplication>
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAdminPassword' : ActorMethod<[string, string], Result>,
  'updateApplicationStatus' : ActorMethod<
    [bigint, ApplicationStatus],
    undefined
  >,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];